version: "3.9"
services:
  postgres:
    image: postgres:15
    ports:
      - ${EXTERNAL_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: containers/dev.Dockerfile
    ports:
      - ${PROJECT_PORT_RANGE_START}-${PROJECT_PORT_RANGE_END}:${PROJECT_PORT_RANGE_START}-${PROJECT_PORT_RANGE_END}
    env_file: .env
    volumes:
      - ./scripts:/app/scripts
      - ./packages/app/backend/src:/app/packages/app/backend/src
      - ./packages/app/frontend/src:/app/packages/app/frontend/src
      - ./packages/lib:/app/packages/lib
