name: Build
permissions: 
    packages: write
    contents: write

on:
  - push

jobs:
  build-images:
    name: Build container images and push them to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
  
      - name: Docker meta frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
            images: |
                ghcr.io/${{github.repository}}-frontend

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
            context: .
            file: containers/frontend.generic.dockerfile
            build-args: |
                PACKAGE_PATH=packages/app/frontend
            push: true
            tags: ${{ steps.meta-frontend.outputs.tags }}
            labels: ${{ steps.meta-frontend.outputs.labels }}

      - name: Docker meta backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
            images: |
                ghcr.io/${{github.repository}}-backend

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
            context: .
            file: containers/backend.generic.dockerfile
            build-args: |
                PACKAGE_PATH=packages/app/backend
            push: true
            tags: ${{ steps.meta-backend.outputs.tags }}
            labels: ${{ steps.meta-backend.outputs.labels }}
  dependabot:
    name: 'Set dependabot PR to auto-merge'
    needs:
      - build-images
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
    - name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}