name: Style

on:
  push

jobs:
  lint-fix:
    name: Run eslint and push potentional changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Init
        run: npm run init

      - name: Run eslint and fix
        run: npm run lint:fix

      - name: Check for modifications
        id: git-diff-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
    
      - name: Configure Git
        uses: fregante/setup-git-user@v1

      - name: Commit and push if changed
        if: steps.git-diff-check.outputs.modified == 'true'
        run: |
          git commit -am "style: fix code style"
          git push