name: Style
permissions:
    contents: write

on:
  push

jobs:
  lint-fix:
    name: Run eslint and push potentional changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Init
        run: npm run init

      - name: Run eslint and fix
        run: npm run lint:fix
    
      - name: Configure Git
        uses: fregante/setup-git-user@v1

      - name: Commit and push if changed
        run: |
          git commit -am "style: fix code style" || echo "No changes to commit"
          git push